# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- discover
- master 

strategy:
  matrix:
    linux_425:
      imageName: 'ubuntu-16.04'
      nodeVersion: '4.2.5'

    linux_5010:
      imageName: 'ubuntu-16.04'
      nodeVersion: '5.0.10'

    Windows-core:
      imagename: 'win1803'
      nodeVersion: '4.2.5'

    Windows-core_5010:
      imagename: 'win1803'
      nodeVersion: '5.0.10'

    mac:
      imageName: 'macos-10.14'
      nodeVersion: '4.2.5'

    mac_5010:
      imageName: 'macos-10.14'
      nodeVersion: '5.0.10'

pool:
  vmImage: $(imageName)


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: 
    npm install
    npm install electron@$(nodeVersion)
  displayName: 'npm install'

- script: 
    npm run test
  displayName: 'npm run test'


- task: PowerShell@2
  inputs:
    filePath: 'test/electron-test.ps1'
    errorActionPreference: 'silentlyContinue'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/vsts/.npm/_logs/'
    ArtifactName: 'npm_logs'
    publishLocation: 'Container'