# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- discover
- master 

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
   
    Windows-core:
       imagename: 'win1803'

    mac:
      imageName: 'macos-10.14'

pool:
  vmImage: $(imageName)



steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: PowerShell@2
  inputs:
    filePath: 'test/electron-test.ps1'
    errorActionPreference: 'silentlyContinue'
